# GitHub Labels 定义文件
# 使用方式：通过 github-label-sync 或 actions/labeler 自动同步
# 手动创建：Settings → Labels → New label

labels:
  # ============ 类型标签 ============
  - name: "bug"
    color: "d73a4a"
    description: "功能异常或错误"

  - name: "enhancement"
    color: "a2eeef"
    description: "新功能或改进建议"

  - name: "question"
    color: "d876e3"
    description: "使用疑问或帮助请求"

  - name: "documentation"
    color: "0075ca"
    description: "文档相关改进"

  - name: "security"
    color: "e4e669"
    description: "安全相关问题"

  # ============ 状态标签 ============
  - name: "needs-triage"
    color: "fbca04"
    description: "等待维护者分类处理"

  - name: "needs-discussion"
    color: "e4e669"
    description: "需要进一步讨论"

  - name: "needs-reproduction"
    color: "fef2c0"
    description: "需要提供复现步骤"

  - name: "in-progress"
    color: "0052cc"
    description: "正在处理中"

  - name: "confirmed"
    color: "0e8a16"
    description: "已确认，等待修复"

  - name: "wontfix"
    color: "ffffff"
    description: "不计划修复"

  - name: "duplicate"
    color: "cfd3d7"
    description: "与已有 Issue 重复"

  - name: "invalid"
    color: "e4e669"
    description: "信息不完整或不符合要求"

  - name: "resolved"
    color: "0e8a16"
    description: "已解决"

  # ============ 模块标签 ============
  - name: "module: payment"
    color: "bfd4f2"
    description: "支付下单 / 回调相关"

  - name: "module: alipay"
    color: "1677ff"
    description: "支付宝支付相关"

  - name: "module: wechat"
    color: "07c160"
    description: "微信支付相关"

  - name: "module: merchant"
    color: "f9d0c4"
    description: "商户管理相关"

  - name: "module: order"
    color: "c5def5"
    description: "订单管理相关"

  - name: "module: admin-ui"
    color: "bfe5bf"
    description: "管理后台前端相关"

  - name: "module: deploy"
    color: "fef2c0"
    description: "部署 / 运维相关"

  - name: "module: database"
    color: "d4c5f9"
    description: "数据库 / Prisma 相关"

  - name: "module: docker"
    color: "0db7ed"
    description: "Docker 部署相关"

  - name: "module: vercel"
    color: "000000"
    description: "Vercel 部署相关"

  - name: "module: cloudflare"
    color: "f38020"
    description: "Cloudflare 部署相关"

  # ============ 优先级标签 ============
  - name: "priority: critical"
    color: "b60205"
    description: "紧急，影响核心功能"

  - name: "priority: high"
    color: "e11d48"
    description: "高优先级"

  - name: "priority: medium"
    color: "f97316"
    description: "中等优先级"

  - name: "priority: low"
    color: "84cc16"
    description: "低优先级"

  # ============ 贡献标签 ============
  - name: "good first issue"
    color: "7057ff"
    description: "适合新贡献者的入门任务"

  - name: "help wanted"
    color: "008672"
    description: "欢迎社区协助解决"
